Lecture 5/hw
OKozmovskaia/thuis_eten pull request #5
Opened 2023-11-29 18:41 UTC by OKozmovskaia

2023-11-30 14:36 UTC, ArchieSA requested changes
нужны правки, на разборе еще раз разберу стили

2023-11-30 14:36 UTC, ArchieSA commented on src/components/menu/styles.module.css
> +  margin: 1em 2em;
внешний стиль

2023-11-30 14:36 UTC, ArchieSA commented on src/components/restaurant/styles.module.css
> +  margin: 2em 0;
внешний стиль

2023-11-30 14:36 UTC, ArchieSA commented on src/components/review/styles.module.css
> +  margin: 1em auto;
внешний стиль

2023-11-30 14:36 UTC, ArchieSA commented on src/components/reviews/styles.module.css
> +  margin: 1em 2em;
внешний стиль

2023-11-30 14:36 UTC, ArchieSA commented on src/components/tab/styles.module.css
> +  margin: 0 1em;
внешний стиль

2023-11-30 14:36 UTC, ArchieSA commented on src/pages/main-page/styles.module.css
> +  margin: 2em auto;
внешний стиль

2023-12-04 14:45 UTC, SArchieEdu approved these changes

2023-12-10 09:55 UTC, merged